# Esercizio 1: Indicizzazione booleana

In [1]:

import numpy as np

# 1. Numeri primi da 0 a 20
primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])
print("Numeri primi:", primi)

# 2. Numeri maggiori di 10
maggiori_10 = primi[primi > 10]
print("Numeri primi > 10:", maggiori_10)

# 3. Numeri primi pari
primi_pari = primi[primi % 2 == 0]
print("Numeri primi pari:", primi_pari)


Numeri primi: [ 2  3  5  7 11 13 17 19]
Numeri primi > 10: [11 13 17 19]
Numeri primi pari: [2]


# Esercizio 2: Operazioni su array

In [2]:

# Creazione array 2D
a = np.random.randint(1, 10, (4, 4))
print("Array a:\n", a)

# Array b: 2a e 4a riga
b = a[[1, 3], :]
print("Array b (2a e 4a riga):\n", b)

# Array c: solo 3a riga
c = a[2, :]
print("Array c (3a riga):", c)

# Divisione colonne di a per c
div = a / c
print("a diviso per c (colonna per colonna):\n", div)


Array a:
 [[9 1 2 3]
 [2 9 2 4]
 [9 7 8 5]
 [3 8 9 3]]
Array b (2a e 4a riga):
 [[2 9 2 4]
 [3 8 9 3]]
Array c (3a riga): [9 7 8 5]
a diviso per c (colonna per colonna):
 [[1.         0.14285714 0.25       0.6       ]
 [0.22222222 1.28571429 0.25       0.8       ]
 [1.         1.         1.         1.        ]
 [0.33333333 1.14285714 1.125      0.6       ]]


# Esercizio 3: Seleziona il numero più vicino a 0.5 in un array casuale

In [3]:

array = np.random.rand(10, 3)
print("Array originale:\n", array)

# Trova indice del valore più vicino a 0.5 in ogni riga
indici = np.abs(array - 0.5).argmin(axis=1)

# Fancy indexing per selezionare i valori
valori = array[np.arange(10), indici]
print("Valori più vicini a 0.5 per riga:", valori)


Array originale:
 [[0.01492139 0.77956988 0.09678011]
 [0.17358786 0.43405954 0.11782202]
 [0.62250628 0.71795094 0.31279244]
 [0.95529848 0.97858342 0.15878714]
 [0.62957977 0.84034594 0.21268351]
 [0.64717178 0.72921579 0.8398362 ]
 [0.40212202 0.68090728 0.79606153]
 [0.95127685 0.94179363 0.51432025]
 [0.05931176 0.44555051 0.51765435]
 [0.61515889 0.29541114 0.56801809]]
Valori più vicini a 0.5 per riga: [0.77956988 0.43405954 0.62250628 0.15878714 0.62957977 0.64717178
 0.40212202 0.51432025 0.51765435 0.56801809]


# Esercizio 4: Analisi della Frequenza Cardiaca con NumPy

In [4]:

battiti = np.array([
    68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162,
    163, 164, 163, 162, 100, 90, 97, 72, 60, 70
])

# Frequenza minima
print("Minima:", battiti.min())

# Frequenza massima
print("Massima:", battiti.max())

# Percentuale sopra 120
sopra_120 = battiti > 120
percentuale = sopra_120.sum() / len(battiti) * 100
print("Percentuale sopra 120 bpm:", round(percentuale, 2), "%")


Minima: 60
Massima: 164
Percentuale sopra 120 bpm: 52.38 %
